### ISSUE TITLE
ArgumentError: wrong number of arguments (given 2, expected 1) when calling delete

### ISSUE THREAD

**Issue by matteo95g** [nateleavitt/active-campaign-simple#1]
When I try calling the delete method, it throws an ArgumentError, I'm not sure why: 

```[1] pry(main)> ActiveCampaign.delete('/contacts/' + '79')
ArgumentError: wrong number of arguments (given 2, expected 1)
from /Users/matteoguerrieri/Desktop/active-campaign-simple/lib/active-campaign-simple/request.rb:28:in `delete'
```

I'm following the example on the README.

I noticed that a fix could be adding payload: {} on the method, but not sure why it expects two arguments in `lib/active-campaign-simple/request.rb:28`

```
def delete(path, payload: {})
  request(:delete, path)
end
```

**Comment by nateleavitt** [comment]
Sorry.. just noticed this. I will update the readme :)

**Comment by nateleavitt** [comment]
Actually.. is this still an issue for you? Maybe it's been fixed since you posted this...
